USE [master]
GO
/****** Object:  Database [miroculuspct]    Script Date: 1/18/2016 4:45:18 PM ******/
CREATE DATABASE [miroculuspct]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'miroculuspct', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\miroculuspct.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'miroculuspct_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\miroculuspct_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [miroculuspct] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [miroculuspct].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [miroculuspct] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [miroculuspct] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [miroculuspct] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [miroculuspct] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [miroculuspct] SET ARITHABORT OFF 
GO
ALTER DATABASE [miroculuspct] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [miroculuspct] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [miroculuspct] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [miroculuspct] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [miroculuspct] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [miroculuspct] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [miroculuspct] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [miroculuspct] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [miroculuspct] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [miroculuspct] SET  DISABLE_BROKER 
GO
ALTER DATABASE [miroculuspct] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [miroculuspct] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [miroculuspct] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [miroculuspct] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [miroculuspct] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [miroculuspct] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [miroculuspct] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [miroculuspct] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [miroculuspct] SET  MULTI_USER 
GO
ALTER DATABASE [miroculuspct] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [miroculuspct] SET DB_CHAINING OFF 
GO
ALTER DATABASE [miroculuspct] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [miroculuspct] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [miroculuspct] SET DELAYED_DURABILITY = DISABLED 
GO
USE [miroculuspct]
GO
/****** Object:  Table [dbo].[Concepts]    Script Date: 1/18/2016 4:45:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Concepts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ConceptTypeId] [int] NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Description] [varchar](1024) NULL,
 CONSTRAINT [PK_Concepts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ConceptTypes]    Script Date: 1/18/2016 4:45:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ConceptTypes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
 CONSTRAINT [PK_ConceptTypes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Documents]    Script Date: 1/18/2016 4:45:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Documents](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](1024) NULL,
	[Source] [varchar](2048) NULL,
 CONSTRAINT [PK_Documents] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Graph]    Script Date: 1/18/2016 4:45:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Graph](
	[DocId] [int] NOT NULL,
	[SentenceIndex] [int] NOT NULL,
	[FromConceptId] [int] NOT NULL,
	[ToConceptId] [int] NOT NULL,
	[Relation] [int] NOT NULL,
	[Score] [real] NOT NULL,
	[ModelVersion] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Graph_1] PRIMARY KEY CLUSTERED 
(
	[DocId] ASC,
	[SentenceIndex] ASC,
	[FromConceptId] ASC,
	[ToConceptId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Sentences]    Script Date: 1/18/2016 4:45:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sentences](
	[DocId] [int] NOT NULL,
	[Index] [int] NOT NULL,
	[Sentence] [text] NOT NULL,
 CONSTRAINT [PK_Sentences] PRIMARY KEY CLUSTERED 
(
	[DocId] ASC,
	[Index] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[test]    Script Date: 1/18/2016 4:45:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[test](
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_Graph_ModelVersion]    Script Date: 1/18/2016 4:45:18 PM ******/
CREATE NONCLUSTERED INDEX [IX_Graph_ModelVersion] ON [dbo].[Graph]
(
	[ModelVersion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Concepts]  WITH CHECK ADD  CONSTRAINT [FK_Concepts_ConceptTypes] FOREIGN KEY([ConceptTypeId])
REFERENCES [dbo].[ConceptTypes] ([Id])
GO
ALTER TABLE [dbo].[Concepts] CHECK CONSTRAINT [FK_Concepts_ConceptTypes]
GO
ALTER TABLE [dbo].[Graph]  WITH CHECK ADD  CONSTRAINT [FK_Graph_Concepts_From] FOREIGN KEY([FromConceptId])
REFERENCES [dbo].[Concepts] ([Id])
GO
ALTER TABLE [dbo].[Graph] CHECK CONSTRAINT [FK_Graph_Concepts_From]
GO
ALTER TABLE [dbo].[Graph]  WITH CHECK ADD  CONSTRAINT [FK_Graph_Concepts_To] FOREIGN KEY([ToConceptId])
REFERENCES [dbo].[Concepts] ([Id])
GO
ALTER TABLE [dbo].[Graph] CHECK CONSTRAINT [FK_Graph_Concepts_To]
GO
ALTER TABLE [dbo].[Graph]  WITH CHECK ADD  CONSTRAINT [FK_Graph_Sentences] FOREIGN KEY([DocId], [SentenceIndex])
REFERENCES [dbo].[Sentences] ([DocId], [Index])
GO
ALTER TABLE [dbo].[Graph] CHECK CONSTRAINT [FK_Graph_Sentences]
GO
ALTER TABLE [dbo].[Sentences]  WITH CHECK ADD  CONSTRAINT [FK_Sentences_Documents] FOREIGN KEY([DocId])
REFERENCES [dbo].[Documents] ([Id])
GO
ALTER TABLE [dbo].[Sentences] CHECK CONSTRAINT [FK_Sentences_Documents]
GO
USE [master]
GO
ALTER DATABASE [miroculuspct] SET  READ_WRITE 
GO
